# Generated by Django 5.2.7 on 2025-10-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0006_recommendation_book_recommended_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birt_date',
            new_name='birth_date',
        ),
    ]
